/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.idetronic.subur.service.persistence.AuthorResearchInterestPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AuthorResearchInterest service. Represents a row in the &quot;Subur_AuthorResearchInterest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.AuthorResearchInterestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.AuthorResearchInterestImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see AuthorResearchInterest
 * @see com.idetronic.subur.model.impl.AuthorResearchInterestImpl
 * @see com.idetronic.subur.model.impl.AuthorResearchInterestModelImpl
 * @generated
 */
public interface AuthorResearchInterestModel extends BaseModel<AuthorResearchInterest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author research interest model instance should use the {@link AuthorResearchInterest} interface instead.
	 */

	/**
	 * Returns the primary key of this author research interest.
	 *
	 * @return the primary key of this author research interest
	 */
	public AuthorResearchInterestPK getPrimaryKey();

	/**
	 * Sets the primary key of this author research interest.
	 *
	 * @param primaryKey the primary key of this author research interest
	 */
	public void setPrimaryKey(AuthorResearchInterestPK primaryKey);

	/**
	 * Returns the author ID of this author research interest.
	 *
	 * @return the author ID of this author research interest
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author research interest.
	 *
	 * @param authorId the author ID of this author research interest
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the research interest ID of this author research interest.
	 *
	 * @return the research interest ID of this author research interest
	 */
	public long getResearchInterestId();

	/**
	 * Sets the research interest ID of this author research interest.
	 *
	 * @param researchInterestId the research interest ID of this author research interest
	 */
	public void setResearchInterestId(long researchInterestId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.subur.model.AuthorResearchInterest authorResearchInterest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.AuthorResearchInterest> toCacheModel();

	@Override
	public com.idetronic.subur.model.AuthorResearchInterest toEscapedModel();

	@Override
	public com.idetronic.subur.model.AuthorResearchInterest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}