/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CopyRequest service. Represents a row in the &quot;Subur_CopyRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.CopyRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.CopyRequestImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see CopyRequest
 * @see com.idetronic.subur.model.impl.CopyRequestImpl
 * @see com.idetronic.subur.model.impl.CopyRequestModelImpl
 * @generated
 */
public interface CopyRequestModel extends BaseModel<CopyRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a copy request model instance should use the {@link CopyRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this copy request.
	 *
	 * @return the primary key of this copy request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this copy request.
	 *
	 * @param primaryKey the primary key of this copy request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the copy request ID of this copy request.
	 *
	 * @return the copy request ID of this copy request
	 */
	public long getCopyRequestId();

	/**
	 * Sets the copy request ID of this copy request.
	 *
	 * @param copyRequestId the copy request ID of this copy request
	 */
	public void setCopyRequestId(long copyRequestId);

	/**
	 * Returns the company ID of this copy request.
	 *
	 * @return the company ID of this copy request
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this copy request.
	 *
	 * @param companyId the company ID of this copy request
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this copy request.
	 *
	 * @return the group ID of this copy request
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this copy request.
	 *
	 * @param groupId the group ID of this copy request
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the date created of this copy request.
	 *
	 * @return the date created of this copy request
	 */
	public Date getDateCreated();

	/**
	 * Sets the date created of this copy request.
	 *
	 * @param dateCreated the date created of this copy request
	 */
	public void setDateCreated(Date dateCreated);

	/**
	 * Returns the status of this copy request.
	 *
	 * @return the status of this copy request
	 */
	public int getStatus();

	/**
	 * Sets the status of this copy request.
	 *
	 * @param status the status of this copy request
	 */
	public void setStatus(int status);

	/**
	 * Returns the subur item ID of this copy request.
	 *
	 * @return the subur item ID of this copy request
	 */
	public long getSuburItemId();

	/**
	 * Sets the subur item ID of this copy request.
	 *
	 * @param suburItemId the subur item ID of this copy request
	 */
	public void setSuburItemId(long suburItemId);

	/**
	 * Returns the from email address of this copy request.
	 *
	 * @return the from email address of this copy request
	 */
	@AutoEscape
	public String getFromEmailAddress();

	/**
	 * Sets the from email address of this copy request.
	 *
	 * @param fromEmailAddress the from email address of this copy request
	 */
	public void setFromEmailAddress(String fromEmailAddress);

	/**
	 * Returns the requester name of this copy request.
	 *
	 * @return the requester name of this copy request
	 */
	@AutoEscape
	public String getRequesterName();

	/**
	 * Sets the requester name of this copy request.
	 *
	 * @param requesterName the requester name of this copy request
	 */
	public void setRequesterName(String requesterName);

	/**
	 * Returns the reason of this copy request.
	 *
	 * @return the reason of this copy request
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this copy request.
	 *
	 * @param reason the reason of this copy request
	 */
	public void setReason(String reason);

	/**
	 * Returns the organization of this copy request.
	 *
	 * @return the organization of this copy request
	 */
	@AutoEscape
	public String getOrganization();

	/**
	 * Sets the organization of this copy request.
	 *
	 * @param organization the organization of this copy request
	 */
	public void setOrganization(String organization);

	/**
	 * Returns the date responsed of this copy request.
	 *
	 * @return the date responsed of this copy request
	 */
	public Date getDateResponsed();

	/**
	 * Sets the date responsed of this copy request.
	 *
	 * @param dateResponsed the date responsed of this copy request
	 */
	public void setDateResponsed(Date dateResponsed);

	/**
	 * Returns the respond text of this copy request.
	 *
	 * @return the respond text of this copy request
	 */
	@AutoEscape
	public String getRespondText();

	/**
	 * Sets the respond text of this copy request.
	 *
	 * @param respondText the respond text of this copy request
	 */
	public void setRespondText(String respondText);

	/**
	 * Returns the responsed by user ID of this copy request.
	 *
	 * @return the responsed by user ID of this copy request
	 */
	public long getResponsedByUserId();

	/**
	 * Sets the responsed by user ID of this copy request.
	 *
	 * @param responsedByUserId the responsed by user ID of this copy request
	 */
	public void setResponsedByUserId(long responsedByUserId);

	/**
	 * Returns the responsed by user uuid of this copy request.
	 *
	 * @return the responsed by user uuid of this copy request
	 * @throws SystemException if a system exception occurred
	 */
	public String getResponsedByUserUuid() throws SystemException;

	/**
	 * Sets the responsed by user uuid of this copy request.
	 *
	 * @param responsedByUserUuid the responsed by user uuid of this copy request
	 */
	public void setResponsedByUserUuid(String responsedByUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.CopyRequest copyRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.CopyRequest> toCacheModel();

	@Override
	public com.idetronic.subur.model.CopyRequest toEscapedModel();

	@Override
	public com.idetronic.subur.model.CopyRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}