/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the HChartSeries service. Represents a row in the &quot;Subur_HChartSeries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.HChartSeriesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.HChartSeriesImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see HChartSeries
 * @see com.idetronic.subur.model.impl.HChartSeriesImpl
 * @see com.idetronic.subur.model.impl.HChartSeriesModelImpl
 * @generated
 */
public interface HChartSeriesModel extends BaseModel<HChartSeries> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h chart series model instance should use the {@link HChartSeries} interface instead.
	 */

	/**
	 * Returns the primary key of this h chart series.
	 *
	 * @return the primary key of this h chart series
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h chart series.
	 *
	 * @param primaryKey the primary key of this h chart series
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this h chart series.
	 *
	 * @return the uuid of this h chart series
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this h chart series.
	 *
	 * @param uuid the uuid of this h chart series
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the h chart series ID of this h chart series.
	 *
	 * @return the h chart series ID of this h chart series
	 */
	public long getHChartSeriesId();

	/**
	 * Sets the h chart series ID of this h chart series.
	 *
	 * @param hChartSeriesId the h chart series ID of this h chart series
	 */
	public void setHChartSeriesId(long hChartSeriesId);

	/**
	 * Returns the series name of this h chart series.
	 *
	 * @return the series name of this h chart series
	 */
	@AutoEscape
	public String getSeriesName();

	/**
	 * Sets the series name of this h chart series.
	 *
	 * @param seriesName the series name of this h chart series
	 */
	public void setSeriesName(String seriesName);

	/**
	 * Returns the color of this h chart series.
	 *
	 * @return the color of this h chart series
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this h chart series.
	 *
	 * @param color the color of this h chart series
	 */
	public void setColor(String color);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.HChartSeries hChartSeries);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.HChartSeries> toCacheModel();

	@Override
	public com.idetronic.subur.model.HChartSeries toEscapedModel();

	@Override
	public com.idetronic.subur.model.HChartSeries toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}