/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the HChartData service. Represents a row in the &quot;Subur_HChartData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.HChartDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.HChartDataImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see HChartData
 * @see com.idetronic.subur.model.impl.HChartDataImpl
 * @see com.idetronic.subur.model.impl.HChartDataModelImpl
 * @generated
 */
public interface HChartDataModel extends BaseModel<HChartData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a h chart data model instance should use the {@link HChartData} interface instead.
	 */

	/**
	 * Returns the primary key of this h chart data.
	 *
	 * @return the primary key of this h chart data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this h chart data.
	 *
	 * @param primaryKey the primary key of this h chart data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this h chart data.
	 *
	 * @return the uuid of this h chart data
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this h chart data.
	 *
	 * @param uuid the uuid of this h chart data
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the h chart data ID of this h chart data.
	 *
	 * @return the h chart data ID of this h chart data
	 */
	public long getHChartDataId();

	/**
	 * Sets the h chart data ID of this h chart data.
	 *
	 * @param hChartDataId the h chart data ID of this h chart data
	 */
	public void setHChartDataId(long hChartDataId);

	/**
	 * Returns the title of this h chart data.
	 *
	 * @return the title of this h chart data
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this h chart data.
	 *
	 * @param title the title of this h chart data
	 */
	public void setTitle(String title);

	/**
	 * Returns the y axis title of this h chart data.
	 *
	 * @return the y axis title of this h chart data
	 */
	@AutoEscape
	public String getYAxisTitle();

	/**
	 * Sets the y axis title of this h chart data.
	 *
	 * @param yAxisTitle the y axis title of this h chart data
	 */
	public void setYAxisTitle(String yAxisTitle);

	/**
	 * Returns the x axis title of this h chart data.
	 *
	 * @return the x axis title of this h chart data
	 */
	@AutoEscape
	public String getXAxisTitle();

	/**
	 * Sets the x axis title of this h chart data.
	 *
	 * @param xAxisTitle the x axis title of this h chart data
	 */
	public void setXAxisTitle(String xAxisTitle);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.HChartData hChartData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.HChartData> toCacheModel();

	@Override
	public com.idetronic.subur.model.HChartData toEscapedModel();

	@Override
	public com.idetronic.subur.model.HChartData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}