/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SuburConfig service. Represents a row in the &quot;Subur_Config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.SuburConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.SuburConfigImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see SuburConfig
 * @see com.idetronic.subur.model.impl.SuburConfigImpl
 * @see com.idetronic.subur.model.impl.SuburConfigModelImpl
 * @generated
 */
public interface SuburConfigModel extends BaseModel<SuburConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subur config model instance should use the {@link SuburConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this subur config.
	 *
	 * @return the primary key of this subur config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subur config.
	 *
	 * @param primaryKey the primary key of this subur config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this subur config.
	 *
	 * @return the ID of this subur config
	 */
	public long getId();

	/**
	 * Sets the ID of this subur config.
	 *
	 * @param id the ID of this subur config
	 */
	public void setId(long id);

	/**
	 * Returns the key of this subur config.
	 *
	 * @return the key of this subur config
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this subur config.
	 *
	 * @param key the key of this subur config
	 */
	public void setKey(String key);

	/**
	 * Returns the description of this subur config.
	 *
	 * @return the description of this subur config
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this subur config.
	 *
	 * @param description the description of this subur config
	 */
	public void setDescription(String description);

	/**
	 * Returns the config of this subur config.
	 *
	 * @return the config of this subur config
	 */
	@AutoEscape
	public String getConfig();

	/**
	 * Sets the config of this subur config.
	 *
	 * @param config the config of this subur config
	 */
	public void setConfig(String config);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.SuburConfig suburConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.SuburConfig> toCacheModel();

	@Override
	public com.idetronic.subur.model.SuburConfig toEscapedModel();

	@Override
	public com.idetronic.subur.model.SuburConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}