/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model.impl;

import com.idetronic.subur.model.SuburConfig;
import com.idetronic.subur.model.SuburConfigModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SuburConfig service. Represents a row in the &quot;Subur_Config&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.subur.model.SuburConfigModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SuburConfigImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see SuburConfigImpl
 * @see com.idetronic.subur.model.SuburConfig
 * @see com.idetronic.subur.model.SuburConfigModel
 * @generated
 */
public class SuburConfigModelImpl extends BaseModelImpl<SuburConfig>
	implements SuburConfigModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subur config model instance should use the {@link com.idetronic.subur.model.SuburConfig} interface instead.
	 */
	public static final String TABLE_NAME = "Subur_Config";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "key_", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "config", Types.CLOB }
		};
	public static final String TABLE_SQL_CREATE = "create table Subur_Config (id_ LONG not null primary key,key_ VARCHAR(75) null,description VARCHAR(75) null,config TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table Subur_Config";
	public static final String ORDER_BY_JPQL = " ORDER BY suburConfig.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Subur_Config.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.subur.model.SuburConfig"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.subur.model.SuburConfig"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.subur.model.SuburConfig"),
			true);
	public static long KEY_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.subur.model.SuburConfig"));

	public SuburConfigModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SuburConfig.class;
	}

	@Override
	public String getModelClassName() {
		return SuburConfig.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("key", getKey());
		attributes.put("description", getDescription());
		attributes.put("config", getConfig());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String key = (String)attributes.get("key");

		if (key != null) {
			setKey(key);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String config = (String)attributes.get("config");

		if (config != null) {
			setConfig(config);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getKey() {
		if (_key == null) {
			return StringPool.BLANK;
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_columnBitmask |= KEY_COLUMN_BITMASK;

		if (_originalKey == null) {
			_originalKey = _key;
		}

		_key = key;
	}

	public String getOriginalKey() {
		return GetterUtil.getString(_originalKey);
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getConfig() {
		if (_config == null) {
			return StringPool.BLANK;
		}
		else {
			return _config;
		}
	}

	@Override
	public void setConfig(String config) {
		_config = config;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SuburConfig.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SuburConfig toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SuburConfig)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SuburConfigImpl suburConfigImpl = new SuburConfigImpl();

		suburConfigImpl.setId(getId());
		suburConfigImpl.setKey(getKey());
		suburConfigImpl.setDescription(getDescription());
		suburConfigImpl.setConfig(getConfig());

		suburConfigImpl.resetOriginalValues();

		return suburConfigImpl;
	}

	@Override
	public int compareTo(SuburConfig suburConfig) {
		long primaryKey = suburConfig.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SuburConfig)) {
			return false;
		}

		SuburConfig suburConfig = (SuburConfig)obj;

		long primaryKey = suburConfig.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SuburConfigModelImpl suburConfigModelImpl = this;

		suburConfigModelImpl._originalKey = suburConfigModelImpl._key;

		suburConfigModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SuburConfig> toCacheModel() {
		SuburConfigCacheModel suburConfigCacheModel = new SuburConfigCacheModel();

		suburConfigCacheModel.id = getId();

		suburConfigCacheModel.key = getKey();

		String key = suburConfigCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			suburConfigCacheModel.key = null;
		}

		suburConfigCacheModel.description = getDescription();

		String description = suburConfigCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			suburConfigCacheModel.description = null;
		}

		suburConfigCacheModel.config = getConfig();

		String config = suburConfigCacheModel.config;

		if ((config != null) && (config.length() == 0)) {
			suburConfigCacheModel.config = null;
		}

		return suburConfigCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", key=");
		sb.append(getKey());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", config=");
		sb.append(getConfig());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.subur.model.SuburConfig");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key</column-name><column-value><![CDATA[");
		sb.append(getKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>config</column-name><column-value><![CDATA[");
		sb.append(getConfig());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SuburConfig.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SuburConfig.class
		};
	private long _id;
	private String _key;
	private String _originalKey;
	private String _description;
	private String _config;
	private long _columnBitmask;
	private SuburConfig _escapedModel;
}